version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: michelle_db
      POSTGRES_USER: sanjik
      POSTGRES_PASSWORD: 1

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8001:8000"
    volumes:
      - ./media:/app/media
    depends_on:
      - db


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./media:/app/media
    depends_on:
      - django
      - fastapi



volumes:
  postgres_data: