version: '3.8'

services:
  db:
    image: postgres:14.7
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
    command: python manage.py runserver 0.0.0.0:8000

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    depends_on:
      - db


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - django
      - fastapi



volumes:
  static_volume:
  media_volume:
  db: