# Generated by Django 5.0.6 on 2024-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='svgs',
            field=models.ManyToManyField(blank=True, to='dishes.svg'),
        ),
    ]
