# Generated by Django 5.0.6 on 2024-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_svgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(default='ahahaha', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_kg',
            field=models.CharField(default='ahgaghag', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(default='aasdasd', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_tu',
            field=models.CharField(default='asdasd', max_length=120),
            preserve_default=False,
        ),
    ]
