# Generated by Django 5.0.6 on 2024-05-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_remove_category_title_category_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dishes',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategories',
        ),
        migrations.AlterModelTable(
            name='svg',
            table='svgs',
        ),
    ]
