# Generated by Django 5.0.6 on 2024-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_remove_dish_text_remove_dish_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='text_en',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
