# Generated by Django 5.0.6 on 2024-06-07 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_dish_weight_subcategory_custom_black_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='advice_en',
            field=models.TextField(default=datetime.datetime(2024, 6, 7, 9, 27, 17, 146044, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='advice_kg',
            field=models.TextField(default=datetime.datetime(2024, 6, 7, 9, 27, 21, 432299, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='advice_ru',
            field=models.TextField(default=datetime.datetime(2024, 6, 7, 9, 27, 24, 820465, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='advice_tu',
            field=models.TextField(default=datetime.datetime(2024, 6, 7, 9, 27, 29, 742761, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
