# Generated by Django 5.0.6 on 2024-06-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0010_dish_advice_en_dish_advice_kg_dish_advice_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='number',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='number',
        ),
    ]
